title: Legolas
email: niels.claes@kuleuven.be
description: >-
  The Legolas code
baseurl: "/the-legolas-code"
url: "localhost:4000"
permalink: pretty

aux_links:
  "The Legolas code on GitHub":
    - "https://github.com/n-claes/legolas"
aux_links_new_tab: true
back_to_top: false

footer_content: "Legolas is licensed under the <a href=\"https://www.gnu.org/licenses/gpl-3.0.html\">GPL-3.0 License.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

color_scheme: light

# Build settings
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
