name: docs

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    runs-on: ubuntu-latest

    # only run on PR or push to develop, skip on master
    if: ${{ contains(github.base_ref, 'develop') || contains(github.ref, 'refs/heads/develop') }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Fix version for now, 3.4 throws an error (see #101)
        pip install markdown==3.3.7
        pip install ford graphviz
        sudo apt-get install graphviz
        pip install -U sphinx
        pip install numpydoc sphinx-rtd-theme lazy-object-proxy==1.4 sphinx-autoapi

    - name: Generate documentation
      run: |
        cd docs
        python generate_docs.py develop

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ contains(github.ref, 'refs/heads/develop') }}
      with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: n-claes/legolas.science-dev
          publish_branch: main
          publish_dir: ./docs
          cname: dev.legolas.science
          enable_jekyll: true
          full_commit_message: 'dev: deploy n-claes/legolas@${{ github.sha }}'

  stable:
    runs-on: ubuntu-latest

    # only run on push to master, skip for develop
    if: ${{ contains(github.ref, 'refs/heads/master') }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ford graphviz
        sudo apt-get install graphviz
        pip install -U sphinx
        pip install numpydoc sphinx-rtd-theme lazy-object-proxy==1.4 sphinx-autoapi

    - name: Generate documentation
      run: |
        cd docs
        python generate_docs.py stable

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_STABLE }}
          external_repository: n-claes/legolas.science-stable
          publish_branch: main
          publish_dir: ./docs
          cname: legolas.science
          enable_jekyll: true
          full_commit_message: 'stable: deploy n-claes/legolas@${{ github.sha }}'
