name: pylbo-core

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CC: /usr/bin/gcc-9
  FC: /usr/bin/gfortran-9
  LEGOLASDIR: /home/runner/work/legolas/legolas

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy matplotlib f90nml tqdm psutil pytest-mpl pytest-timeout
        cd post_processing
        python setup.py develop

    - name: Install Legolas dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gfortran-9
        sudo apt-get -y install cmake
        sudo apt-get install libblas-dev
        sudo apt-get install liblapack-dev
        gfortran-9 --version
        cmake --version

    - name: Compile Legolas
      run: sh setup_tools/buildlegolas.sh

    - name: Test Pylbo core
      run: |
        cd tests/pylbo_tests
        pytest --mpl --mpl-results-path=results --verbose

    - name: Archive failed logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: failed_logs
        path: tests/pylbo_tests/results

