name: regression

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CC: /usr/bin/gcc-9
  FC: /usr/bin/gfortran-9
  LEGOLASDIR: /home/runner/work/legolas/legolas
  ARPACK_ROOT: /home/runner/work/legolas/legolas/tests/arpack-ng

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy matplotlib f90nml tqdm psutil pytest-mpl
        cd post_processing
        python setup.py develop

    - name: Install Legolas dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get -y install cmake
        sudo apt-get install gfortran-9
        sudo apt-get install libblas-dev
        sudo apt-get install liblapack-dev
        gfortran-9 --version

    - name: Cache ARPACK
      id: arpack-cache
      uses: actions/cache@v1
      with:
        path: tests/arpack-ng/
        key: ${{ runner.os }}-arpackv1

    - name: Build ARPACK
      if: steps.arpack-cache.outputs.cache-hit != 'true'
      run: |
        cd tests
        git clone https://github.com/opencollab/arpack-ng.git
        cd arpack-ng
        mkdir build
        mkdir installed
        cd build
        cmake -DEXAMPLES=OFF -DMPI=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=../installed ..
        make -j 2
        sudo make -j 2 install

    - name: Compile Legolas
      run: sh setup_tools/buildlegolas.sh

    - name: Run regression tests
      run: |
        cd tests/regression_tests
        pytest regression.py -v

    - name: Archive failed logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failed_logs
        path: tests/regression_tests/image_comparisons
        if-no-files-found: warn
