name: website

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ford graphviz
        sudo apt-get install graphviz
        pip install -U sphinx
        pip install numpydoc sphinx-rtd-theme lazy-object-proxy==1.4 sphinx-autoapi

    - name: Build Fortran docs
      run: |
        cd docs
        ford build_ford.md

    - name: Build Python docs
      run: |
        cd docs
        sh build_sphinx.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          cname: legolas.science
          enable_jekyll: true
          full_commit_message: "deploy ${{ github.sha }}: ${{ github.event.head_commit.message }}"
          force_orphan: true
